---
abstract: 'Common utilities for IRC-related tasks'
author:
  - 'Hinrik Örn Sigurðsson <hinrik.sig@gmail.com>'
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102342, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IRC-Utils
no_index:
  directory:
    - t
    - xt
    - utils
requires:
  perl: 5.008001
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=IRC-Utils
  homepage: http://search.cpan.org/dist/IRC-Utils/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hinrik/irc-utils.git
version: 0.02
x_authority: cpan:HINRIK
